server:
  port: 1323
  host: "localhost"

database:
  provider: "postgres"

hashing:
  algorithm: "argon2"

postgres:
    url: "postgres://postgres:password@localhost:5432/identity-server"

mailer:
  provider: 'smtp'

cache:
  provider: "redis"

redis:
  url: "localhost:6379"
  username: ""
  password: ""

smtp:
  host: "localhost"
  port: 25
  username: "guest"
  password: "guest"
  from: "no-reply@localhost"
  from_name: "Identity Server"
  tls: false
  default_credentials: false

auth:
  credential_verification:
    secret: "your-credential-verification-secret"
    lifetime_minutes: 30

  session:
    lifetime_hours: 24
    trusted_lifetime_hours: 720

  refresh_token:
    secret: "your-refresh-token-secret"

  access_token:
    lifetime_minutes: 5
    issuer: "identity-server"
    private_key: "your-rsa-2048-private-key"
    public_key: "your-rsa-2048-public-key"

